- CharacterFloatInfo/CharacterFloatInfo.cs
A floating window for viewing character information
> CharacterFloatInfo

- AutoChooseAttackPart/AutoChooseAttackPart.cs
Add Mod:AutoChooseAttackPart v1.0.0
> Add Mod:AutoChooseAttackPart

- CharacterFloatInfo/CharacterFloatInfo.cs
Add Some Little Settings For CharacterFloatInfo
> Add Settings For CharacterFloatInfo

- ShowMap/ShowMap.cs
> Add mod ShowMap

- CharacterFloatInfo/CharacterFloatInfo.cs
Support float info in MassageWindow(when mouse enter actor faceholder)
Show Mood in float info(hided by default)
> CharacterFloatInfo v1.0.4:

- CMakeLists.txt
可以考虑使用 VS 2017 自带的 CMake，经测试没有任何问题
> Use a lower version of CMake that comes with VS2017

- genvsproj.sh
允许 WSL 用户从 Bash on Windows 生成 Project，依赖 #16
> Allow VS project generation from WSL

- NoMoreTrash/Info.json
- NoMoreTrash/NoMoreTrash.cs
Auto drop trash booty in battle.
> Add Mod:NoMoreTrash v1.0.0

- ShowBiographyOfTheDead/Info.json
- ShowBiographyOfTheDead/ShowBiographyOfTheDead.cs
Wont show “………………” in biography when favor is not enough
> Update ShowBiographyOfTheDead to V1.0.1:

- CharacterFloatInfo/CharacterFloatInfo.cs
- CharacterFloatInfo/Info.json
> Update Character to v1.0.6:

- LKX_NewGameActor/Info.json
Fix [build 58](https://travis-ci.com/phorcys/Taiwu_mods/builds/88050358)
> Fix build failure due to bad `Requirements` argument

- CharacterFloatInfo/CharacterFloatInfo.cs
- CharacterFloatInfo/Info.json
> Update CharacterFloatInfo to v1.0.8:

- ManpowerWork/Info.json
- ManpowerWork/ManpowerWork.cs
> 任意资源格子使用人力 1.0

- BaseResourceMod/BaseResourceMod.cs
- genvsproj.cmd
baseResourceMod中添加注释。
添加游戏中一品至九品对应的颜色编码的注释，以方便mod开发者。
正在学习练手中，也希望能做点贡献。
> baseResourceMod中添加注释

- CharacterFloatInfo/CharacterFloatInfo.cs
从9品灰到1品红。前世太吾村村民不变色，太吾传人显示明黄色。
把其他的去掉了，重新pull
> 显示前世名字时会根据前世的品级显示名字颜色。

- CharacterFloatInfo/CharacterFloatInfo.cs
> 可以显示人物身上的最佳（最高品质）物品了；

- CharacterFloatInfo/CharacterFloatInfo.cs
在浮動訊息框中顯示人物特性（圖形介面）
額外加插選項，決定是否顯示原本隱藏了的2類特性：(1)是否童男童女，(2)入魔狀態
> 在浮動訊息框中顯示人物特性

- HomeShopSort/HomeShopSort.cs
- HomeShopSort/Info.json
> Add Mod HomeShopSort v1.0.0：

- HomeShopSort/HomeShopSort.cs
- HomeShopSort/Info.json
fix bug which makes characterfloatinfo forcely disabled, this fix wont change game behavior
> Fix Bug For HomeShopSort

- HomeShopSort/HomeShopSort.cs
- HomeShopSort/Info.json
Show workEfficiency in HomeMap
> Update HomeShopSort to v1.l.0:

- CharacterFloatInfo/CharacterFloatInfo.cs
- CharacterFloatInfo/Info.json
新增：可查看太吾/同道人、人物天賦、背包重量；標示可學的才藝。
另外，已修正圖片顯示不同步的問題。
=============================
暫時想改的都改好了，我將會改其他MOD。
多謝指教。
> 新增：可查看太吾/同道人、人物天賦；標示可學的才藝；修正圖片不同步

- DoNotDisturb/DoNotDisTurb.cs
- DoNotDisturb/Info.json
添加勿扰模式 包括 屏蔽1.NPC乞讨事件，2.屏蔽入魔事件提示，3.附加较艺助手功能（凑数用的）
> add mod DoNotDisturb

- HomeShopSort/HomeShopSort.cs
- HomeShopSort/Info.json
> update to v1.1.1

- SaveLoadBtns/Info.json
- SaveLoadBtns/SaveLoadBtns.cs
> 方便游戏的S/L进度

- CharacterFloatInfo/CharacterFloatInfo.cs
修正人物天賦錯誤 (當打開個人資訊介面再關後, 舊有天賦不會刪除.已修復) 
修正死人時出紅字 (當Cursor指向死人墓穴時, 會引發多處出紅字)
新增: 個人資訊介面內的同道人, 可顯示訊穴息窗
新增: 個人資訊介面內的輪回前世人物, 可顯示訊息窗
個人資訊介面內的人物關系圖, 可顯示訊息窗
- 但當在太吾村地圖點擊死人墓穴的TAB後(或打開大地圖鄰區的NPC列表後), 未有訊息窗;  (待修正) 
- 且之後在個人資訊介面中的關系表不能顯示詳細訊息內容. (待修正)
> 修正: 人物天賦的錯誤 / 修正點指死人墓穴時會出紅字

- CharacterFloatInfo/CharacterFloatInfo.cs
- CharacterFloatInfo/Info.json
添加了显示可学功法的功能
最佳功法与可学功法都不再显示隐藏功法“吐纳法”了
> 添加了显示可学功法的功能

- CharacterFloatInfo/CharacterFloatInfo.cs
- CharacterFloatInfo/Info.json
- HomeShopSort/HomeShopSort.cs
- HomeShopSort/Info.json
cant work when there are more than one base home（other mod may make this happen）
Update HomeShopSort:
Show 'Empty' when building has no man in
change color a little
> Fix Bug For CharacterFloatInfo and HomeShopSort:

- CharacterFloatInfo/CharacterFloatInfo.cs
增加:小型浮動窗類型,
對話時選人物顯示浮動窗,
鄰格人物顯示浮動窗
> New features

- ResourceShop/Info.json
- ResourceShop/ResourceShop.cs
> ADD Mod ResourceShop v1.0.0：

- CharacterFloatInfo/CharacterFloatInfo.cs
- CharacterFloatInfo/Info.json
- HomeShopSort/HomeShopSort.cs
- HomeShopSort/Info.json
Because xiangfang has new effect.
> Update CharacterFloatInfo And HomeShopSort For GameVersion 0.1.4

- KeyBoardShortCut/Info.json
- KeyBoardShortCut/KeyBoardShortCut.cs
在对话窗口使用Esc/鼠标右键选择最后一个选项
在对话窗口增加小键盘选择功能
> feat(KeyBoardShortCut): 增加对话窗口相关快捷键

- CMakeModules/UseCSharp.cmake
> 打包mod只排除c#源文件及隐藏文件

- SwitchTheBook/Info.json
- SwitchTheBook/SwitchTheBook.cs
> First commit of mod "SwitchTheBook"

- SamsaraLock/SamsaraLock.cs
我向被我毒死若干次的太吾发誓，
真的修复了不生效问题&死后变性问题
> 1.1.1fix，不要再有更多过期MOD的受害者啦！

- CharacterFloatInfo/CharacterFloatInfo.cs
- CharacterFloatInfo/Info.json
可在地格人物肖像上显示了
显示人物银钱
显示相枢化程度
显示熟练度未满50%的准可教功法
在太吾肖像上显示促织福缘
显示商人隐藏信息
修复报错
> V1.4.4更新 对应游戏V2.2.2

- BaseResourceMod/BaseResourceMod.cs
- BaseResourceMod/CSVPatch.cs
- BaseResourceMod/Info.json
- BaseResourceMod/README.md
- BaseResourceMod/SpriteLoadHelper.cs
- BaseResourceMod/SpritePatch.cs
> 基础资源框架1.0.14: 解决内存泄露问题

- CMakeLists.txt
- genvsproj.cmd
I though it'd handy for future people not to have to change anything locally to be able to build, this seemed like the only thing preventing that.
Batch files are a bit obtuse to read so I added a few comments to my processing steps.
> Discover taiwu install path instead of hardcoding

- CharacterFloatInfo/CharacterFloatInfo.cs
- NpcScan/ActorItem.cs
- NpcScan/Patch.cs
- UseStorageMaterial/UseStorageMaterial.cs
> 修复浮动信息和NPCScan
